Homework 2
================
Yueran Pan

## Problem 1

``` r
 subway_df = 
  read_csv(file = "./hw2_data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  na = c(".", "NA", ""),
  col_types = cols(
     Route8 = col_character(),
     Route9 = col_character(),
     Route10 = col_character(),
     Route11 = col_character()
     )
 )
```

``` r
names(subway_df)
```

    ##  [1] "Division"           "Line"               "Station Name"      
    ##  [4] "Station Latitude"   "Station Longitude"  "Route1"            
    ##  [7] "Route2"             "Route3"             "Route4"            
    ## [10] "Route5"             "Route6"             "Route7"            
    ## [13] "Route8"             "Route9"             "Route10"           
    ## [16] "Route11"            "Entrance Type"      "Entry"             
    ## [19] "Exit Only"          "Vending"            "Staffing"          
    ## [22] "Staff Hours"        "ADA"                "ADA Notes"         
    ## [25] "Free Crossover"     "North South Street" "East West Street"  
    ## [28] "Corner"             "Entrance Latitude"  "Entrance Longitude"
    ## [31] "Station Location"   "Entrance Location"

``` r
#clean names to lower case
subway_df = janitor::clean_names(subway_df)
#check new name
names(subway_df)
```

    ##  [1] "division"           "line"               "station_name"      
    ##  [4] "station_latitude"   "station_longitude"  "route1"            
    ##  [7] "route2"             "route3"             "route4"            
    ## [10] "route5"             "route6"             "route7"            
    ## [13] "route8"             "route9"             "route10"           
    ## [16] "route11"            "entrance_type"      "entry"             
    ## [19] "exit_only"          "vending"            "staffing"          
    ## [22] "staff_hours"        "ada"                "ada_notes"         
    ## [25] "free_crossover"     "north_south_street" "east_west_street"  
    ## [28] "corner"             "entrance_latitude"  "entrance_longitude"
    ## [31] "station_location"   "entrance_location"

``` r
#Keep the column specified
subway_df = select (
    subway_df, 
    line:entry, 
    vending,
    ada
    )

#Convert the entry variable from character to logical variable using case_match function

subway_df = mutate(subway_df,
  entry = case_match(
    entry, 
    "YES" ~ TRUE,
    "NO"~ FALSE
  )
)
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

About this dataset:

The dataset originally contained records of NYC subway entrances and
exits, including 32 variables, such as line, station name, routes
served, entry permission, vending availability, and so on. I cleaned the
column names to lower case, retained the specified columns (line,
station, name, station latitude / longitude, routes served, entry,
vending, entrance type, and ADA compliance), and converted column
`entry` from a character variable to a logical variable. The resulting
dataset has 1,868 rows and 19 columns. It is not yet completely tidy
because route names are spread across multiple columns, from route1 to
route11.

### Prob1, Q1: How many distinct stations are there?

``` r
stations_df = distinct(
  subway_df,
  line,
  station_name
)
str(stations_df)
```

    ## tibble [465 × 2] (S3: tbl_df/tbl/data.frame)
    ##  $ line        : chr [1:465] "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name: chr [1:465] "25th St" "36th St" "45th St" "53rd St" ...

There are 465 distinct stations, identified by the combination of line
and station name.

### Prob1, Q2: How many stations are ADA compliant?

``` r
ada_df = filter(subway_df, ada == TRUE)

ada_df = distinct(
  ada_df,
  ada,
  line,
  station_name)
str(ada_df)
```

    ## tibble [84 × 3] (S3: tbl_df/tbl/data.frame)
    ##  $ ada         : logi [1:84] TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ line        : chr [1:84] "4 Avenue" "4 Avenue" "4 Avenue" "42nd St Shuttle" ...
    ##  $ station_name: chr [1:84] "Atlantic Av-Barclays Ctr" "DeKalb Av" "Pacific St" "Grand Central" ...

There are 84 ADA compliant stations.

### Prob1,Q3: What proportion of station entrances / exits without vending allow entrance?

``` r
wo_vending_df = filter(
  subway_df,
  vending == "NO"
)
wo_vend_entry = pull(wo_vending_df,entry)
mean(wo_vend_entry == TRUE)
```

    ## [1] 0.3770492

37.70% of station entrances/exits without vending allow entrance.

### Prob1,Q4: Reformat data so that route number and route name are distinct variables. How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

``` r
# Reshape route columns into route number and route name.
subway_long_df = pivot_longer(
  subway_df,
  route1:route11,
  names_to = "route_number",
  names_prefix = "route",
  values_to = "route_name"
)
subway_long_df = drop_na(subway_long_df, route_name)

# Keep records serving the A train.
a_train_df = filter(
  subway_long_df,
  route_name == "A"
)
# Count distinct A train stations.
a_stations_df = distinct(
  a_train_df,
  line,
  station_name
)
#check
str(a_stations_df)
```

    ## tibble [60 × 2] (S3: tbl_df/tbl/data.frame)
    ##  $ line        : chr [1:60] "42nd St Shuttle" "8 Avenue" "8 Avenue" "8 Avenue" ...
    ##  $ station_name: chr [1:60] "Times Square" "125th St" "145th St" "14th St" ...

``` r
# Count distinct ADA-compliant A train stations.
a_ada_df = filter(
  a_train_df,
  ada == TRUE
)
a_ada_stations_df = distinct(
  a_ada_df,
  line,
  station_name
)
#final check
str(a_ada_stations_df)
```

    ## tibble [17 × 2] (S3: tbl_df/tbl/data.frame)
    ##  $ line        : chr [1:17] "8 Avenue" "8 Avenue" "8 Avenue" "8 Avenue" ...
    ##  $ station_name: chr [1:17] "14th St" "168th St - Washington Heights" "175th St" "34th St" ...

Among all 60 A train stations served, 17 of them are ADA compliant.

## Problem 2

``` r
mr_df = readxl::read_excel(
 "./hw2_data/202610 Trash Wheel Collection Data.xlsx",
 sheet = "Mr. Trash Wheel",
range = "A2:N742"
)|>
janitor::clean_names()|>
drop_na(dumpster) |>
mutate(
  sports_balls = round(sports_balls),
  sports_balls = as.integer(sports_balls),
  year = as.integer(year),
  plastic_bottles = as.integer(plastic_bottles),
  wheel= "Mr. Trash Wheel"
  )

prof_df = readxl::read_excel(
 "./hw2_data/202610 Trash Wheel Collection Data.xlsx",
 sheet = "Professor Trash Wheel",
range = "A2:M139",
#saw a "dive" in G137 of prof sheet...???Thus I treat this nonnumeric value "dive" as missing. 
na = c("", "dive")
)|>
janitor::clean_names()|>
drop_na(dumpster) |>
mutate(
  year = as.integer(year),
  plastic_bottles = as.integer(plastic_bottles),
  wheel= "Professor Trash Wheel")

gwynnda_df = readxl::read_excel(
 "./hw2_data/202610 Trash Wheel Collection Data.xlsx",
 sheet = "Gwynnda the Good Wheel of the W",
range = "A2:L394",
)|>
janitor::clean_names()|>
drop_na(dumpster) |>
mutate(
  year = as.integer(year),
  plastic_bottles = as.integer(plastic_bottles),
  wheel= "Gwynnda")
```

### combine 3 sheets

``` r
trash_df = bind_rows(
  mr_df,
  prof_df,
  gwynnda_df
)
str(trash_df)
```

    ## tibble [1,269 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:1269] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:1269] "May" "May" "May" "May" ...
    ##  $ year              : int [1:1269] 2014 2014 2014 2014 2014 2014 2014 2014 2014 2014 ...
    ##  $ date              : POSIXct[1:1269], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:1269] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:1269] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : int [1:1269] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:1269] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:1269] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:1269] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:1269] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:1269] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : int [1:1269] 7 5 6 6 7 5 3 6 6 7 ...
    ##  $ homes_powered     : num [1:1269] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ wheel             : chr [1:1269] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...

### count

``` r
prof_wt_just_in_case = drop_na(prof_df, weight_tons)
prof_wt = pull(prof_wt_just_in_case, weight_tons)
prof_sum_wt = mean(prof_wt)*length(prof_wt)
prof_sum_wt
```

    ## [1] 294.96

``` r
gwynnda_June22 = filter(
   gwynnda_df,
   month == "June",
   year == 2022
)

gwynnda_June22 = drop_na(gwynnda_June22, cigarette_butts)
gwynnda_cigbt = pull(gwynnda_June22, cigarette_butts)

gwynnda_count_cigbt = mean(gwynnda_cigbt)*length(gwynnda_cigbt)
gwynnda_count_cigbt
```

    ## [1] 18120

The total weight of trash collected by Professor Trash Wheel was
`prof_sum_wt` tons. `gwynnda_count_cigbt` cigarette butts were collected
by Gwynnda in June of 2022.

## Problem 3
